
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.minecraft]
			pale_oak = true

		[types.wood_type.regions_unexplored]
			alpha = true
			baobab = true
			blackwood = true
			blue_bioshroom = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = true
			eucalyptus = true
			green_bioshroom = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			mauve = true
			palm = true
			pine = true
			pink_bioshroom = true
			redwood = true
			socotra = true
			willow = true
			yellow_bioshroom = true

		[types.wood_type.gtceu]
			rubber = true

	[types.leaves_type]

		[types.leaves_type.minecraft]
			pale_oak = true

		[types.leaves_type.regions_unexplored]
			alpha = true
			apple_oak = true
			bamboo = true
			baobab = true
			blackwood = true
			magnolia = true
			cypress = true
			dead = true
			dead_pine = true
			eucalyptus = true
			flowering = true
			golden_larch = true
			kapok = true
			larch = true
			maple = true
			mauve = true
			orange_maple = true
			palm = true
			pine = true
			blue_magnolia = true
			pink_magnolia = true
			redwood = true
			red_maple = true
			brimwood = true
			enchanted_birch = true
			small_oak = true
			silver_birch = true
			socotra = true
			white_magnolia = true
			willow = true
			ashen = true

		[types.leaves_type.gtceu]
			rubber = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.create]
			window_pane = true
			window = true

	[entries.leaves_type]

		[entries.leaves_type.regions_unexplored]
			shrub = true

